### PR TITLE
Optimize event processing performance

### LINKED ISSUE #65: Large cmake builds are slow - syspolicyd
I'm just beginning to track this down but I've noticed that, when I do a project build here using ninja/cmake it will be terribly slow with BlockBlock enabled. If I disable BlockBlock the compile proceeds as expected. 

A quick look shows that `syspolicyd` is getting hit really hard with BlockBlock enabled. With it disabled there's no such bottleneck. 

I will try to regress this a little further, of course, but wondered if it made any obvious sense? 

When it is enabled, there are lots of

```
info	00:00:25.068108-0400	syspolicyd	looking up ticket: <private>, 2, 0
info	00:00:25.106178-0400	syspolicyd	completing lookup: <private>, 3
```

and when disabled, they don't happen. 

- - -
macOS Ventura / 13.5
MBP m1 / 64gb
cmake version 3.27.1
ninja --version 1.11.1

Jamf / MDM university stuff.

### LINKED ISSUE #68: CPU surge and Thread explosion on Xcode Build
I noticed the amount of threads and CPU usage goes dramatically up while doing xcode builds. It slows the whole system down with it resulting in regressions. Should be able to replicate by running BlockBlock and then running xcode builds or run make for a decently big project in terminal - Terminal commands run super slow especially when doing make builds

### PR DESCRIPTION
**Pull request by art-divin**
Resolves #68; Resolves #65

## Description

This PR addresses for-loop iterations not being concurrent, as well as resolves a couple of issues with the project, specifically - Xcode static code analyzer showed a bug, and Sentry needed to be updated due to an issue with the linker in later versions of Xcode/clang.

## Context

In my attempt to resolve issues while Xcode is running swift compiler, I made a small investigation, and the following was uncovered:

1. when Daemon is running, in its `main` function `Monitor` instance is created
2. then `-[Monitor start]` is called from the same `main` function of the Daemon
3. in `-[Monitor start]` there is the following code:
```objc
FileCallbackBlock block = ^(File* file)
    {
...
            //process file event
            [self processEvent:file];
        }
    };
...
//start monitoring
    started = [self.fileMon start:events count:sizeof(events)/sizeof(events[0]) csOption:csNone callback:block];
```
5. for every file registered by the Monitor (are all files in the system registered, or only some? I do not know exactly), callback is executed. It means that during compilation in Xcode, every file that is being created, written etc. produces these events. Xcode compilation happens in parallel on different cores, thus produces hundreds if not thousands of events.
6. Events arrive via the callback block to `-[Monitor processEvent:]`
7. Upon processing of the event, a "plugin" is being looked up in all registered "plugins":
```objc
// ...that cares about the path/file that was just created
plugin = [self findPlugin:file];
```
8. found "plugin" is an instance of `PluginBase`, the same I have mentioned in the beginning
9. message `-[PluginBase isMatch:]` is sent then, which uses `regex` to match against the given "event", where "event' is a file system event

As can be seen in the sample I have provided in the previous message, ICU library is responsible for such enormous CPU consumption.

## Conclusion

Due to the nature of file processing, it is not that easy to optimize the process when there is such big bulk operation with file reads/writes occurs in the system. 

That being said, there are a few techniques which might improve the situation not only for Xcode, but for all other applications/file operations as well:

1. use parallel enumeration when evaluating "plugin" against the given event
2. use parallel enumeration when searching for a "plugin" in all registered plugins
3. exit early in case the event should be "ignored"

### CODE REVIEW

File: Cartfile [hunk 1]
```diff
@@ -1 +1 @@
-github "getsentry/sentry-cocoa" "6.0.10"
+github "getsentry/sentry-cocoa" "8.16.1"
```
Comment (art-divin) [inline Cartfile:1]: I had to update Sentry due to an error:

```
Projects/BlockBlock/Carthage/Checkouts/sentry-cocoa/Sources/Sentry/SentrySwizzle.m:104:26: error: a function declaration without a prototype is deprecated in all versions of C [-Werror,-Wstrict-prototypes]
swizzledClassesDictionary()
                         ^
                          void
```

File: Daemon/Daemon/Monitor.m [hunk 2]
```diff
@@ -506,6 +506,18 @@ -(void)processEvent:(File*)file
         goto bail;
     }
 
+    //passive mode?
+    // no rule, just allow (but log)
+    if(YES == [preferences.preferences[PREF_PASSIVE_MODE] boolValue])
```
Comment (art-divin) [inline Daemon/Daemon/Monitor.m:511]: Check for passive mode can be made before `Event` instance is created. Losing a little bit of logging, i.e. `-[Event description]` provides representation of `Item`, which prints `[event.plugin itemName:event];` and `[event.plugin itemObject:event];`. 

For your consideration.

File: Daemon/Daemon/Monitor.m [hunk 3]
```diff
@@ -531,7 +543,32 @@ -(void)processEvent:(File*)file
     
     //dbg msg
     logMsg(LOG_DEBUG, [NSString stringWithFormat:@"created event: %@", event]);
-    
+
+    //matches last event?
+    // if so, ignore the event
+    if(YES == [event isRelated:self.lastEvent])
```
Comment (art-divin) [inline Daemon/Daemon/Monitor.m:549]: Before matching rules against the given event, we can exit earlier if the event is the same as the last processed event.

File: Daemon/Daemon/Monitor.m [hunk 4]
```diff
@@ -705,19 +706,13 @@ -(PluginBase*)findPlugin:(File*)file
     __block PluginBase* plugin = nil;
     
     //look for plugin that can handle path
-    [plugins enumerateObjectsUsingBlock:^(PluginBase* currentPlugin, NSUInteger index, BOOL* stop)
```
Comment (art-divin) [inline Daemon/Daemon/Monitor.m:708]: `enumerateObjectsUsingBlock:` was blocking current thread while enumerating through the collection of the registered plugins sequentially. `indexOfObjectWithOptions:NSEnumerationConcurrent` will block the current thread, but also would fire multiple threads at the same time for looking up the needed plugin.

Might work, might not work. For your consideration.

File: Daemon/Daemon/PluginBase.m [hunk 5]
```diff
@@ -76,27 +76,25 @@ -(BOOL)isMatch:(File*)file
     path = file.destinationPath;
     
     //match?
-    [self.regexes enumerateObjectsUsingBlock:^(NSRegularExpression* regex, NSUInteger index, BOOL * _Nonnull stop) {
-        
+    [self.regexes enumerateObjectsWithOptions:NSEnumerationConcurrent usingBlock:^(NSRegularExpression* _Nonnull regex, NSUInteger idx, BOOL * _Nonnull stop) {
```
Comment (art-divin) [inline Daemon/Daemon/PluginBase.m:79]: `enumerateObjectsUsingBlock:` was blocking the current thread while evaluating regular expressions against the given file path. `indexOfObjectWithOptions:NSEnumerationConcurrent` will block the current thread, but also would fire multiple threads for evaluating regular expressions on different CPU cores at the same time.

Might work, might not work. For your consideration.

File: Daemon/Daemon/Rules.m [hunk 6]
```diff
@@ -221,8 +221,8 @@ -(Rule*)find:(Event*)event
         //check all (process's) rules
         // same startup item and same path
         // note: * is a wildcard, meaning any match
-        for(Rule* rule in self.rules[key][KEY_RULES])
-        {
+        NSArray<Rule *> *rules = self.rules[key][KEY_RULES];
+        NSUInteger idx = [rules indexOfObjectWithOptions:NSEnumerationConcurrent passingTest:^BOOL(Rule * _Nonnull rule, NSUInteger idx, BOOL * _Nonnull stop) {
```
Comment (art-divin) [inline Daemon/Daemon/Rules.m:225]: Lookup of the rules is also moved to concurrent perform. 

Might work, might not work. For your consideration.

File: Daemon/Daemon/XPCListener.m [hunk 7]
```diff
@@ -204,7 +204,8 @@ -(BOOL)listener:(NSXPCListener *)listener shouldAcceptNewConnection:(NSXPCConnec
     
     //step 2: validate
     // check that client is signed with Objective-See's and it's BlockBlock
-    if(errSecSuccess != (status = SecTaskValidateForRequirement(taskRef, (__bridge CFStringRef)(requirement))))
+    OSStatus validateForRequirementStatus = SecTaskValidateForRequirement(taskRef, (__bridge CFStringRef)(requirement));
```
Comment (art-divin) [inline Daemon/Daemon/XPCListener.m:207]: I have ran static analyzer, and it showed that the assignment of the `SecTaskValidateForRequirement` was not being evaluated in the condition, thus most likely it was not behaving correctly.

For your consideration. Might work, might not. 🤞🏻

Comment (objective-see) [reply Daemon/Daemon/XPCListener.m:207]: not that the analyzer is wrong, but we can just re-use `status` here like so:

```
status = SecTaskValidateForRequirement(taskRef, (__bridge CFStringRef)(requirement));
if(errSecSuccess != status) {
   goto bail;
}
 ```
 
Could always put in some logging those error cases if we wanted to print out why it failed (e.g. what `status` is)

File: Cartfile (hunk 1 above)
Comment (objective-see) [reply Cartfile:1]: I'm going to remove Sentry as 
1. I don't like the external dependency (that as you pointed out, often needs updating)
2. It raises GDPR concerns

Comment (art-divin) [reply Cartfile]: Thank you for your answer. I can remove it easily in a separate MR, along with Carthage integration 👍🏻

Comment (art-divin) [reply Cartfile]: Reverted the change

File: Daemon/Daemon/XPCListener.m (hunk 7 above)
Comment (art-divin) [reply Daemon/Daemon/XPCListener.m]: Thank you! I have missed the fact that this is the last check for `status` variable. In general I refuse to reuse variables. They are optimized out anyway, so it is a matter of avoiding bugs in future 👍🏻

**Comment by art-divin** [comment]
Should also resolve #10
